Fix root module name handling in build info collection
jfrog/jfrog-cli-core pull request #1201
Opened 2024-07-15 12:39 UTC by EyalDelarea

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

## Bug Description:
When collecting build information for different packages, if the module name is not specified in the descriptor file or provided as a CLI argument, it defaults to an empty string. This results in an error from the Artifactory server, stating that the module ID cannot be null.

```
16:22:54 [Error] server response: 400 
{
  "errors": [
    {
      "status": 400,
      "message": "Module id name cannot be null!"
    }
  ]
}
```

### In previous CLI versions, the default value was ":", which prevented crashes.

## Fix:
If no module ID is provided, the default will now be set to the base directory of the module. This aligns with the default behavior of package descriptors init scripts.
As a last reasort the module name will resolve to "module" to be displayed at the UI and not fail on publish.

2024-07-15 13:06 UTC, eyalbe4 requested changes

2024-07-15 13:06 UTC, eyalbe4 commented on artifactory/commands/npm/npmcommand.go
> +// Resolves to the base directory name if a module name is not provided in package.json or CLI command.
Resolves to the base directory name ... --> Returns the project's root directory name ...

Let's also add to function's description the case where the module name is provided.

2024-07-15 13:39 UTC, yahavi commented on artifactory/commands/npm/npmcommand.go
> +		moduleName = path.Base(nc.workingDirectory)
Shouldn't be filepath.Join?

2024-07-21 07:19 UTC, EyalDelarea commented
@yahavi i've changed the function to return error if fails to get working dir.
let me know what you think 🚀

2024-07-30 06:53 UTC, yahavi commented on common/build/buildutils.go
> +		return
Let's put here checkerr and remove it from all other users of ResolveBaseModuleName

2024-07-30 07:21 UTC, merged

2024-08-09 01:51 UTC, kunkka-m commented
<img width="401" alt="image" src="https://github.com/user-attachments/assets/71e27590-0896-487e-b928-24fd91094cd1">
<img width="570" alt="image" src="https://github.com/user-attachments/assets/298b807f-9a46-4d2f-828a-649472ee1461">
I used the latest version of jfrog-cli(2.63.0), but this issue still happened

2024-08-09 01:54 UTC, kunkka-m commented
Oh, This MR is to dev branch!

2024-09-13 02:00 UTC, lincoohe commented
Hi @EyalDelarea ,it should be the **build-publish** issue  instead of **bce** issue.