Package manager login command - `Npm`, `Yarn`, `Pip`, `Pipenv`, `Poetry`,`Go`, `Nuget`, `Dotnet`
jfrog/jfrog-cli-core pull request #1285
Opened 2024-10-25 15:20 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----
# PR Description

## Title
**Add `PackageManagerLoginCommand` for Configuring Package Managers in JFrog CLI**

## Description
This PR introduces the `PackageManagerLoginCommand`, a unified command for configuring package managers to use JFrog Artifactory. It enables registry setup and authentication across various project types, automatically handling tool-specific settings based on the selected project.

### Supported Package Managers
- **npm**: Configures registry and authentication in the `.npmrc` file.
- **Yarn**: Sets up registry and authentication in the `.yarnrc` or `.yarnrc.yml` file.
- **Pip**: Configures PyPI repository URL in the `pip.conf` file.
- **Pipenv**: Sets the global index URL in the `pip.conf` file.
- **Poetry**: Manages repository and authentication in the `pyproject.toml` file.
- **Go**: Configures the `GOPROXY` (persistent) environment variable to use Artifactory.
- **NuGet**: Adds repositories and authentication in the `NuGet.config` file.
- **dotnet**: Configures repositories and authentication in the `NuGet.config` file.

### Supported Auth Types
- Token-based, Basic (username/password), and Anonymous.

### Testing
- Unit tests validate configuration updates for each package manager.

2024-11-10 13:31 UTC, eyalbe4 requested changes

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/commands/python/poetry.go
> +	}
Let's simplify to - 
```
	if err := viper.ReadInConfig(); err != nil {
		return errorutils.CheckErrorf("Failed to read pyproject.toml: %s", err.Error())
	}
```
Let's do the same for the `err = viper.WriteConfig()` line below.

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/commands/python/python.go
>  func GetPypiRepoUrlWithCredentials(serverDetails *config.ServerDetails, repository string, isCurationCmd bool) (*url.URL, string, string, error) {
Let's check if this function can be made private.
The same goes for the other functions in this file.

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/commands/python/python.go
>  	if err != nil {
Can be softened to - 
```
	if err := gofrogcmd.RunCmd(configCmd); err != nil {
```

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/utils/npm/config-delete.go
> +
Following our talk, let's delete this file.

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/utils/npm/config-set.go
> +
Let'e rena,e this file from `config-set.go` to `config_set.go`, so that ti is more aligned with go's naming conventions for files.

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/utils/npm/config-set.go
> +func ConfigSet(key, value, executablePath string) error {
Let's add a description for this function, to male it easier for the random reader landing on this file.

2024-11-10 13:31 UTC, eyalbe4 commented on artifactory/utils/yarn/configdelete.go
> +
Following our talk, let's delete this file.

2024-11-10 15:10 UTC, sverdlov93 commented on artifactory/commands/buildtoollogin/buildtoollogin.go
> +package buildtoollogin
How do you suggest to distinguish between build tool (pip, pipenv, poetry) and package type (pypi)

for example here:
func buildToolToPackageType(buildTool project.ProjectType) (string, error) {
	switch buildTool {
	case project.Npm, project.Yarn:
		return repository.Npm, nil
	case project.Pip, project.Pipenv, project.Poetry:
		return repository.Pypi, nil
	case project.Go:
		return repository.Go, nil
	default:
		return "", errorutils.CheckErrorf("unsupported build tool: %s", buildTool)
	}
}

@eyalbe4

2024-11-17 09:12 UTC, omerzi reviewed
Perhaps we could move the `npm` and `yarn` config set/get functionality out of `utils` and place it under a more focused `javascript` package (similar to how the python package handles pip, poetry, etc). This could also be a good opportunity to merge any overlapping code between the two for better reusability and maintainability. What do you think?

2024-11-18 14:15 UTC, merged