New audit-npm command
jfrog/jfrog-cli-core pull request #132
Opened 2021-06-14 14:48 UTC by talarian1

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-06-15 11:59 UTC, yahavi requested changes
Looks good!

I think that since a lot of the npm code is shared between Artifactory and Xray commands, we should probably export the shared code to a common NpmUtils class. The Xray command should not know the Artifactory command.

2021-06-15 11:59 UTC, yahavi commented on xray/commands/audit/npm.go
> +		// Because we are dealing with a
?

2021-06-15 11:59 UTC, yahavi commented on xray/commands/audit/npm.go
> +		if sons, ok := treeMap[father]; ok {
Let's keep the convention of parent-child
```suggestion
		parent := NpmPackageTypeIdentifier + dependency.GetPathToRoot()[0][0]
		if children, ok := treeMap[father]; ok {
```

2021-06-15 11:59 UTC, yahavi commented on xray/commands/audit/npm.go
> +func buildXrayDependencyTree(treeHelper map[string][]string, node string) *services.GraphNode {
```suggestion
func buildXrayDependencyTree(treeHelper map[string][]string, nodeId string) *services.GraphNode {
```

2021-06-20 08:25 UTC, yahavi requested changes

2021-06-20 08:25 UTC, yahavi commented on xray/commands/audit/npm.go
> +package scan
```suggestion
package audit
```

2021-06-20 08:25 UTC, yahavi commented on xray/commands/audit/npm_test.go
> +package scan
```suggestion
package audit
```

2021-06-20 09:02 UTC, yahavi commented
One more thing - please add an option to read the resolver configuration at the `.jfrog/projects/npm.yaml`. This way we will allow users to download dependencies from Artifactory, which is mandatory IMO.

2021-06-20 12:49 UTC, eyalbe4 requested changes

2021-06-20 12:49 UTC, eyalbe4 commented on artifactory/commands/npm/installorci.go
>  func NewNpmCommandArgs(npmCommand string) *NpmCommandArgs {
Missing new-line before function.

2021-06-20 12:49 UTC, eyalbe4 commented on xray/commands/audit/npm.go
> +type XrAuditNpmCommand struct {
XrAuditNpmCommand --> AuditNpmCommand

2021-06-20 12:49 UTC, eyalbe4 commented on xray/commands/audit/npm.go
> +	typeRestriction  npm.TypeRestriction
```npm.TypeRestriction``` is under the ```artifactory/commands``` path, but we're under ```xrat/commands```.
We should move shared resources to be under a common package, which can be shared between Artifactory and Xray.
I think there are other components that need to be moved, such as ```npm.NewNpmCommandArgs```.

2021-06-20 12:49 UTC, eyalbe4 commented on xray/commands/audit/npm.go
> +func NewXrAuditNpmCommand() *XrAuditNpmCommand {
NewXrAuditNpmCommand --> NewAuditNpmCommand

2021-06-20 12:57 UTC, eyalbe4 requested changes

2021-06-20 12:57 UTC, eyalbe4 commented on xray/commands/audit/npm.go
> +
Redundant new-line.

2021-06-30 17:05 UTC, talarian1 commented
#143 includes those changes.

2021-06-30 17:05 UTC, closed without merging