Yarn improvements
jfrog/jfrog-cli-core pull request #194
Opened 2021-07-28 07:12 UTC by asafgabai

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-07-31 08:39 UTC, eyalbe4 requested changes

2021-07-31 08:39 UTC, eyalbe4 commented on artifactory/commands/npm/installorci.go
>  		return errors.New(fmt.Sprintf("Two errors occurred:\n %s\n %s", restoreErr.Error(), err.Error()))
We should wrap this with CheckError.

2021-07-31 08:39 UTC, eyalbe4 commented on artifactory/commands/utils/npmcmdutils.go
> +func BackupFile(filePath, backupPath string) (restore func() error, err error) {
Let's add a description for this function, specifically explaining the returned value and how it should be used. The same goes for the ```createRestoreFileFunc``` function used by this function. The entire code flow is not trivial and requires some explaining to make the reading easier.
I'd be happy to review this again after the descriptions are added, to see if it's easier for me to understand the code flow.

I also suggest we unit test this function.

2021-07-31 08:39 UTC, eyalbe4 commented on artifactory/commands/utils/npmcmdutils.go
> +		if err := os.Rename(backupPath, filePath); err != nil {
We're not allowed to use ```s.Rename``` because it fails inside a docker container. We should use ```fileutils.MoveFile``` instead.

2021-08-06 08:09 UTC, eyalbe4 approved these changes

2021-08-09 15:38 UTC, asafgabai commented on go.mod
> +replace github.com/jfrog/jfrog-client-go => github.com/asafgabai/jfrog-client-go v0.18.1-0.20210809145706-c8a0dfb1d46d
Reminder for myself to update this before the merge.

2021-08-15 14:28 UTC, merged