Introduce transfer config command
jfrog/jfrog-cli-core pull request #395
Opened 2022-05-24 15:59 UTC by yahavi

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-06-15 08:16 UTC, eyalbe4 requested changes

2022-06-15 08:16 UTC, eyalbe4 commented on artifactory/commands/transferconfig/utils.go
> +		return buffer, err
Missing CheckError here.

2022-06-15 08:16 UTC, eyalbe4 commented on artifactory/commands/transferconfig/utils.go
> +			return nil, err
Missing CheckError here.

2022-06-15 08:16 UTC, eyalbe4 commented on artifactory/commands/transferconfig/utils.go
> +		if err != nil {
Missing CheckError here.

2022-06-15 08:16 UTC, eyalbe4 commented on artifactory/commands/transferconfig/utils.go
> +			retErr = closeErr
Missing CheckError here.

2022-06-15 08:16 UTC, eyalbe4 commented on artifactory/commands/transferconfig/utils.go
> +	_, retErr = fileWriter.Write([]byte(configXml))
Missing CheckError here.

2022-06-21 08:52 UTC, yahavi commented on artifactory/commands/transferconfig/transferconfig.go
> +func (tcc *TransferConfigCommand) verifyArtifactoryServers(targetServicesManager artifactory.ArtifactoryServicesManager, sourceArtifactoryVersion string) error {
Will be implemented in a follow-up PR + https://github.com/jfrog/config-import/pull/3

2022-06-21 08:53 UTC, yahavi commented on artifactory/commands/transferconfig/transferconfig.go
> +	if len(*localRepositories) > 1 {
Changed to "number of users > 2"

2022-06-21 09:07 UTC, merged