Transfer data cmd
jfrog/jfrog-cli-core pull request #432
Opened 2022-06-28 13:13 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-06-28 22:22 UTC, eyalbe4 requested changes
I think we should simulate the following scenario - 
During phase 1 or phase 2, jfrog-cli looses connectivity with the source Artifactory instance. The source instance will simply not recieves the chunks. JFrog CLI in this case will just log the error and move on to the next chunk. The chunks that failed to be sent will never be sent again.

2022-06-29 07:01 UTC, RobiNino commented on artifactory/commands/transferfiles/api.go
> +// Fill tokens batch till full. Return if no new tokens are available.
Added description above polIUploads

2022-06-29 07:53 UTC, RobiNino commented on artifactory/commands/transferfiles/migration.go
> +func (m *migrationPhase) run() error {
As discussed, will look into it in future PRs

2022-06-29 07:56 UTC, gailazar300 commented on utils/log/log.go
> +func CreateLogFile() (*os.File, error) {
This is the existing logging mechanism - I moved those functions from the cli to core cause the 'transfer progress bar" was moved to core and used this functionality.

2022-06-29 08:21 UTC, RobiNino commented on artifactory/commands/transferfiles/transfer.go
> +	}
We check it for every repo separately in `verifyRepoExistsInTarget`

2022-06-29 08:39 UTC, RobiNino commented on artifactory/commands/transferfiles/utils.go
> +var curProcessedUploadChunks = 0
Will do as part of the structure change of the phases in future PRs

2022-06-29 08:48 UTC, RobiNino commented on artifactory/commands/transferfiles/utils.go
> +func handleFilesOfCompletedChunk(chunkFiles []FileUploadStatusResponse) {
@gailazar300 's commit which was not included in this PR involves in this area.

2022-06-29 08:56 UTC, RobiNino commented on artifactory/commands/transferfiles/utils.go
> +		if strings.HasPrefix(filepath.Base(file), repoKey) {
Noted. Will replace with regexp later on

2022-06-29 09:09 UTC, merged