Gracefully handle interruptions in SaaS migration
jfrog/jfrog-cli-core pull request #452
Opened 2022-07-07 15:37 UTC by yahavi

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
    
* Capture the interruption signal (ctrl+c) and send the stop command to the data-transfer plugin
* Better handling node detection (depends on https://github.com/jfrog/jfrog-client-go/pull/611)

2022-07-10 13:30 UTC, RobiNino requested changes
Like!
One more thing left to handle beside the comments I left on code:
1. We need to add a stop check to `uploadByChunks`. This would probably require exposing the stop mechanism to `transferManager`

2022-07-10 13:30 UTC, RobiNino commented on utils/progressbar/transferfileprogressbar.go
> +func (t *TransferProgressMng) StopGracefully() {
Might need to hold the bar returned from this function, and abort it with drop=true in `Quit()`. See how we handle other headlines and check if it is necessary.

2022-07-18 09:07 UTC, yahavi commented on artifactory/commands/transferfiles/transfer.go
> +	requestsNumForStop     = 5
I replaced it with (number of running nodes) * 3.
This should be enough according to https://www.wikiwand.com/en/Coupon_collector%27s_problem

2022-08-02 09:29 UTC, merged

2022-08-03 04:14 UTC, eyalbe4 reviewed
Some minor comments.

2022-08-03 04:14 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +			log.Debug("All running nodes stopped successfully")
All running nodes stopped successfully
-->
Transfer on all Artifactory nodes stopped successfully

2022-08-03 04:14 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +func stopAllRunningNodes(srcUpService *srcUserPluginService, runningNodes []string) {
stopAllRunningNodes --> stopTransferOnArtifactoryNodes

(less of a scary name :) Let's rename the test corresponding test function as well).

2022-08-03 04:14 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +	for i := 0; i < len(runningNodes)*3; i++ {
Let's explain here why this loop iterates over `len(runningNodes)*3`.

2022-08-03 04:14 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +	log.Debug("Running nodes to stop:", remainingNodesToStop)
Running nodes to stop --> Running Artifactory nodes to stop transfer on