Add Poetry support
jfrog/jfrog-cli-core pull request #466
Opened 2022-07-20 14:44 UTC by talarian1

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-07-24 10:51 UTC, sverdlov93 commented on utils/coreutils/techutils.go
> +	Poetry: {
Add exclude slice like Npm has under Pip for pipenv and poetry indicators

2022-07-24 10:51 UTC, sverdlov93 commented on xray/audit/python/python_test.go
> +	transitiveChildNode := audit.GetAndAssertNode(t, childNode.Nodes, "packaging:21.3")
```suggestion
if assert.NotNil(t, childNode) {
	transitiveChildNode := audit.GetAndAssertNode(t, childNode.Nodes, "packaging:21.3")
	......
```
so it won't panic if childnodes is nil

2022-07-24 10:51 UTC, sverdlov93 commented on .github/workflows/test.yml
> +        uses: snok/install-poetry@v1
```suggestion
        uses: pip3 install poetry
```

2022-09-11 10:07 UTC, eyalbe4 requested changes

2022-09-11 10:07 UTC, eyalbe4 commented on utils/coreutils/techutils.go
> +	Poetry = "poetry"
@omerzi created a PR which unifies the package managers name across the entire code. Worth synching with him to make the merge easier.

2022-09-11 10:07 UTC, eyalbe4 commented on xray/audit/python/python.go
> +
Redundant new-line.

2022-09-13 17:55 UTC, merged