Transfer - add repository state manager
jfrog/jfrog-cli-core pull request #496
Opened 2022-08-09 18:36 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2022-09-01 07:12 UTC, eyalbe4 requested changes
* We need to undertand why we're calling the `IncrementPhase` in the `handleErrorsFiles` functions. Since this action is part of *phase 2*, for which the progress shows time slots, how come we increase the progress for every error file?
* Can we actually remove the `IncrementPhase` alltogether, and just use `IncrementPhaseBy` with `1` as the increased value?

2022-09-01 09:12 UTC, RobiNino commented
@eyalbe4 ,
Regarding `IncrementPhase` in the `handleErrorsFiles` - the correct total of the progress bar is set in `initProgressBar`, and includes the number of errors files. I think it makes sense to include it in the total and increment as we do know, to show work is being done in every stage of the phase.

2022-09-04 15:41 UTC, eyalbe4 requested changes
I haven't finished going over all the code. I'll continue review it soon.
I'm submitting here what I have so far.

2022-09-04 15:41 UTC, eyalbe4 commented on utils/repostate/statemanager.go
> +dirsLoop:
I tried going through this code, and couldn't understand the logic of these loops. There's a good chance the code does what it is supposed to, but let's see if we can make it easier to read and understanbd.
I'd be happy to review it again your changes.

2022-09-04 15:41 UTC, eyalbe4 commented on utils/repostate/statemanager.go
> +func (sm *RepoStateManager) LookUpNode(relativePath string) (*Node, error) {
Don't we have an issue of thread safety here? If multiple go routine can call this API simultaneously, we should find the best and most efficient way to protect the critical sections of the data structure.
If indeed we have an issue here, and we need to modify the code, I'd be happy to revierw the code again after those changes.

2022-09-08 11:55 UTC, eyalbe4 requested changes
Done reviewing everything.
I'd be happy to review it again following the changes.

2022-12-05 17:25 UTC, closed without merging