Avoid old snapshots/tags cleanup after transfer
jfrog/jfrog-cli-core pull request #516
Opened 2022-08-24 14:25 UTC by asafgabai

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
Turn off the Max Unique Snapshots/Tags setting at the beginning of the transfer-files operation and turn it back on at the end.
There might be more snapshots/tags than the maximum if the Max Unique Snapshots/Tags property was set and no snapshot/tag was uploaded afterward.
In cases like this, we don't want to trigger the cleanup of old snapshots, so we turn off the Max Unique Snapshots/Tags setting during the transfer.
This setting exists only in repositories of these package types: Maven, Gradle, NuGet, Ivy, SBT, and Docker.

2022-08-25 07:48 UTC, omerzi commented on artifactory/commands/transferfiles/transfer.go
> +		if srcMaxUniqueSnapshots != -1 {
Maybe let's add a comment about the -1 meaning?

2022-08-25 08:02 UTC, omerzi commented on artifactory/commands/transferfiles/utils.go
> +	case maven:
I think we can use the Factory Method design pattern in order to create concrete LocalRepositoryParam, and then we can reduce the number of duplicated lines, this also applies to 'updateMaxUniqueSnapshots'

2022-08-25 08:03 UTC, omerzi commented on artifactory/commands/transferfiles/utils.go
> +	case maven:
See comment above about the factory method

2022-08-25 08:05 UTC, omerzi requested changes
Seems good to me overall, I think we can reduce some duplicated code using the Factory method, contact me if you need further explanation on what I mean

2022-08-27 18:12 UTC, eyalbe4 requested changes
I think this PR adds the first API of the `transfer-files` command, which invokes an API on the target instance directly, and not through the `data-transfer` user plugin.
I therefore think we should try pinging the target instance at the very beginning of the transfer process, and fail the command with a clear error message, in case the target is not accessible.

2022-08-27 18:12 UTC, eyalbe4 commented on artifactory/commands/transferfiles/transfer.go
> +		}
I think that this code should be put inside a defer clause, right after calling the new `handleMaxUniqueSnapshots` as I suggested above. Actually, this code can be inside a function named `restoreTargetMaxUniqueSnapshots`. This function can be a returned value of the `handleMaxUniqueSnapshots` function.

2022-08-27 18:12 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +// On repositories of other package types or if an error is thrown, this function returns -1.
On repositories... --> For repositories...

2022-08-27 18:12 UTC, eyalbe4 commented on artifactory/commands/transferfiles/utils.go
> +// On repositories of other package types, this function does nothing.
On repositories... --> For repositories...

2022-08-28 05:54 UTC, asafgabai commented
> I think this PR adds the first API of the `transfer-files` command, which invokes an API on the target instance directly, and not through the `data-transfer` user plugin. I therefore think we should try pinging the target instance at the very beginning of the transfer process, and fail the command with a clear error message, in case the target is not accessible.

We get the repositories list from the target beforehand, so if it's not accessible, it will fail there.

2022-08-28 09:03 UTC, merged