Transfer files - moving errors handling to new phase
jfrog/jfrog-cli-core pull request #551
Opened 2022-09-14 13:38 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----
refactor error retry from phase 2 into a new phase 3.
moving this phase to be the last operation, adding a progress bar to show the progress and count of uploading errors.

2022-09-14 13:39 UTC, attiasas commented
I have read the CLA Document and I hereby sign the CLA

2022-09-14 13:41 UTC, attiasas commented
retry

2022-09-14 13:41 UTC, attiasas commented
recheck

2022-09-16 07:05 UTC, eyalbe4 requested changes
I'd like to review the PR again, following the implementation of the below throughout the code.
* Our convention is to start code comments with an upper case letter. For example, let's change - "// reads an error..." into "// Reads an error..."
* Let's make sure the keep correct grammar when adding comments. For example, notice the following comments. Since it starts with "Reads", it should then include "parses" and not "parse" - 
```
// reads an error file from a given path, parse and populate a given FilesErrors instance with the file information
```

2022-09-16 08:36 UTC, eyalbe4 requested changes

2022-09-16 08:36 UTC, eyalbe4 commented on artifactory/commands/transferfiles/fileserror.go
> +}
The above `phaseStarted` code is good, but let's simplify a bit the code of the `phaseStarted` functions of the other two pahses.
The following - 
```
func (f *filesDiffPhase) phaseStarted() error {
	f.startTime = time.Now()
	err := addNewDiffToState(f.repoKey, f.startTime)
	if err != nil {
		return err
	}

	return err
}
```
can be simplified to - 
```
func (f *filesDiffPhase) phaseStarted() error {
	f.startTime = time.Now()
	return addNewDiffToState(f.repoKey, f.startTime)
}
```
Let's make a similar simplification in last `phaseStarted` function.

2022-09-16 08:36 UTC, eyalbe4 commented on artifactory/commands/transferfiles/fileserror.go
> +		//var failedFiles FilesErrors
Let's remove this commenrt. It's unclear.

2022-09-16 08:36 UTC, eyalbe4 commented on artifactory/commands/transferfiles/fileserror.go
> +	log.Debug("Starting Error-Retry Phase (3) for '", filesCount, "' files")
This debug line seems unnecessary.

2022-09-16 08:36 UTC, eyalbe4 commented on artifactory/commands/transferfiles/transferfileprogress.go
> +	t.phases = append(t.phases, t.barsMng.NewTasksWithHeadlineProg(tasksPhase3, "Phase 3: Retry transferring all files that had upload errors", false, progressbar.GREEN, Files.String()))
Retry transferring all files that had upload errors
-->
Retry transfer failures

2022-09-18 11:24 UTC, merged