Transfer - Refactor how delay artifact handled to support error handle
jfrog/jfrog-cli-core pull request #579
Opened 2022-10-13 12:54 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2022-10-17 18:01 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +		return []string{}, err
return []string{}, err --> return

The same goes for the other retuern statements in this function.

2022-10-17 18:02 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +
Redundant new-line.

2022-10-17 18:04 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +type SplitContentWriter struct {
Let's add a description for this struct. Explain why it is needed.
Let's also describe all of the struct's components.
Also, it looks like this struct doesn't have have to be public.

2022-10-17 18:06 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +	ContentFiles []string
Why does this property need to be public?

2022-10-17 18:09 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +func NewSplitContentWriter(key string, maxRecordsPerFile int, directoryPath string, prefix string) *SplitContentWriter {
This function probably doesn't need to be public.

2022-10-17 18:10 UTC, eyalbe4 commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +func (w *SplitContentWriter) WriteRecord(record interface{}) error {
It looks like this function doesn't have to be public.

2022-10-23 15:18 UTC, yahavi requested changes
Looks good, @attiasas!

2022-10-23 15:18 UTC, yahavi commented on artifactory/commands/transferfiles/delayedartifactshandler_test.go
> +	assert.NoError(t, ioutil.WriteFile(filepath.Join(delaysDirPath, getDelayMockFileName("wrong-"+testRepoKey+"-wrong", 0)), nil, 0644))
This line repeats 6 times:
```go
assert.NoError(t, ioutil.WriteFile(filepath.Join(delaysDirPath, getDelayMockFileName("xxx", 111)), nil, 0644))
```
Can we add a loop or use a dedicated function to reduce code duplication?

2022-10-23 15:18 UTC, yahavi commented on artifactory/commands/transferfiles/fileserror.go
> +	delayCount, err = countDelayFilesContent(delayFiles)
A bit shorter:
```suggestion
	delayFiles, err := getDelayFiles([]string{e.repoKey})
	if err != nil {
		return err
	}
	delayCount, err := countDelayFilesContent(delayFiles)
```

2022-10-23 15:18 UTC, yahavi commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +	maxRecordAllow int
```suggestion
	maxRecordsAllowed int
```

2022-10-23 15:18 UTC, yahavi commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +	// List all the file paths of the files that were generated for the content
```suggestion
	// List of all the paths of the files that were generated for the content
```

2022-10-23 15:18 UTC, yahavi commented on artifactory/commands/transferfiles/delayedartifactshandler.go
> +	return &scw
```suggestion
	return &SplitContentWriter{arrayKey: key, maxRecordAllow: maxRecordsPerFile, dirPath: directoryPath, filePrefix: prefix}
```

2022-10-24 11:33 UTC, yahavi approved these changes

2022-10-24 11:35 UTC, merged