Inhancement for progress bars code
jfrog/jfrog-cli-core pull request #687
Opened 2023-02-08 14:25 UTC by sarao1310

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-02-09 11:58 UTC, eyalbe4 requested changes

2023-02-09 11:58 UTC, eyalbe4 commented on utils/progressbar/transferprogressbarmanager.go
> +				log.Error(err)
Let's add a context perffix to this error message.

2023-02-14 12:54 UTC, eyalbe4 commented
@sarao1310 - I see that there's an unresolved discussion above. Let me know when I can review this PR again.

2023-02-25 20:50 UTC, eyalbe4 requested changes
I see that this PR still has open discussions, so I'm returning it to you @sarao1310.

2023-03-03 15:01 UTC, eyalbe4 requested changes

2023-03-05 10:37 UTC, sarao1310 commented on utils/progressbar/progressbarmng.go
>  func (bm *ProgressBarMng) NewTasksWithHeadlineProg(totalTasks int64, headline string, spinner bool, color Color, windows bool, taskType string) *TasksWithHeadlineProg {
Done

2023-03-07 12:35 UTC, merged