Transfer - Reduce snapshot memory consumption
jfrog/jfrog-cli-core pull request #705
Opened 2023-03-12 12:10 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
Memory consumption was reduced by changing the Node struct used by the snapshot manager.
The repository snapshot will not longer save file names, i.e. when resuming from snapshot any directory that wasn't previously completely transferred will be re-explored. This is a breaking change.

2023-03-15 12:31 UTC, eyalbe4 requested changes

2023-03-15 12:31 UTC, eyalbe4 commented on artifactory/commands/transferfiles/transfer.go
> +	return assertRepositorySpecificStructure()
What is the reason we're running the `assertRepositorySpecificStructure ` check? Isn't ti enough running the `VerifyTransferRunStatusVersion`?

2023-03-16 15:44 UTC, yahavi requested changes

2023-03-16 15:44 UTC, yahavi commented on utils/reposnapshot/node.go
> +	filesCount    uint64
Can be 32
```suggestion
	filesCount    uint32
```

2023-03-16 15:44 UTC, yahavi commented on artifactory/commands/transferfiles/state/utils.go
> +		"You may either downgrade JFrog CLI to the version that was used before, or remove the transfer directory which is located under the JFrog CLI home directory\n" +
"located under the JFrog CLI home directory"
Can we elaborate more about the exact path? I'd prefer that users will be able to work around issues by themselves

2023-03-16 15:44 UTC, yahavi commented on utils/reposnapshot/snapshotmanager_test.go
> +	for i := range node.children {
Why not Go style loop?
```suggestion
	for _, child := range node.children {
```

2023-03-19 15:01 UTC, merged