Upload archive
jfrog/jfrog-cli-core pull request #79
Opened 2021-03-02 08:16 UTC by asafgabai

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2021-03-02 08:18 UTC, asafgabai commented on go.mod
> +replace github.com/jfrog/jfrog-client-go => github.com/asafgabai/jfrog-client-go upload-archive
Reminder for myself to change it back to dev

2021-03-04 16:25 UTC, eyalbe4 requested changes

2021-03-04 16:25 UTC, eyalbe4 commented on artifactory/commands/npm/publish.go
> +	buildArtifacts, e := specutils.ConvertArtifactsDetailsToBuildInfoArtifacts(npc.artifactsDetailsReader)
e --> err

2021-03-07 11:44 UTC, eyalbe4 approved these changes

2021-03-07 14:49 UTC, merged