Improve npm prase depednecy tree
jfrog/jfrog-cli-core pull request #817
Opened 2023-06-01 10:05 UTC by EyalDelarea

- [x] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

2023-06-24 17:39 UTC, eyalbe4 requested changes

2023-06-24 17:39 UTC, eyalbe4 commented on xray/audit/commonutils.go
> +		*exceededDepthCounter += 1
*exceededDepthCounter += 1
-->
*exceededDepthCounter++

2023-07-05 07:47 UTC, EyalDelarea commented
@eyalbe4 I've added before and after screenshots.
Just wanted to make sure we still want this output so i'll merge this.
i've tested it, and it does not effect Frogbot, trying to think if anything else would change from this new output.
Basically it's just another impact path so i shouldn't.

2023-07-20 11:11 UTC, eyalbe4 approved these changes

2023-07-23 07:04 UTC, merged