Fix duplicate rows and added scope for component name
jfrog/jfrog-cli-core pull request #890
Opened 2023-08-07 14:05 UTC by asafambar

- [ ] All [tests](https://github.com/jfrog/jfrog-cli-core#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli-core/actions/workflows/analysis.yml) passed.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

2023-08-07 14:10 UTC, asafambar commented
Curation Xray reports show for each direct dependencies all its blocked packages under curation. Under a direct dependency can be many packages which are similar under different paths, we want to present in the report only one occurrence for each package.
Also added scope for packge name, scope is also part of the component name uniqueness,
according to NPM official desperation of scope:
_"All npm packages have a name. Some package names also have a scope. A scope follows the usual rules for package names (URL-safe characters, no leading dots or underscores). When used in package names, scopes are preceded by an @ symbol and followed by a slash, e.g."_

2023-08-09 06:41 UTC, yahavi requested changes

2023-08-09 06:41 UTC, yahavi commented on xray/commands/curation/audit.go
> +func getNameScopeAndVersion(id, artiUrl, repo, tech string) (downloadUrl, name, scope, version string) {
```suggestion
func getNpmNameScopeAndVersion(id, artiUrl, repo, tech string) (downloadUrl, name, scope, version string) {
```

2023-08-09 06:41 UTC, yahavi commented on xray/commands/curation/audit_test.go
>  			}
Let's use assert.Equal to make the code easier to read. For example:
```go
assert.Equal(t, tt.wantDownloadUrl, gotDownloadUrl, "getNameScopeAndVersion() gotDownloadUrl = %v, want %v", gotDownloadUrl, tt.wantDownloadUrl)

```

2023-08-09 06:45 UTC, yahavi commented on xray/commands/curation/audit.go
> +	packagesStatus *[]*PackageStatus, parent, parentVersion string, visited map[string]struct{}, isRoot bool) {
Let's use set here
```suggestion
	packagesStatus *[]*PackageStatus, parent, parentVersion string, visited datastructures.Set[string], isRoot bool) {
	for _, child := range node.Nodes {, isRoot bool) {
```

2023-08-10 06:36 UTC, yahavi commented on xray/commands/curation/audit_test.go
> +				assert.Equal(t, tt.wantVersion, gotVersion, "getNpmNameScopeAndVersion() gotVersion = %v, want %v", gotVersion, tt.wantVersion)
Please remove the "if"s @asafambar

2023-08-11 13:10 UTC, yahavi approved these changes
LGTM

2023-08-11 13:11 UTC, merged